name: Manual API Regressions

on: 
  workflow_dispatch:
    inputs:
      network:
        description: 'Which network do you want to run regressions against?'     
        required: true
        default: 'dev'

jobs:
  api_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: 0chain/0chainAPI
          token: ${{ secrets.SVC_ACCOUNT_SECRET }}
          
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra
         
      - name: Set env BRANCH
        run: |
         echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV
         echo "BRANCH_UNSANITIZED=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Make Directory for results
        run: mkdir -p ./${BRANCH}/latest

      - name: Run POSTMAN collection
        run: |
           exit_code=0
           newman run "./Postman Collections/0chain-regressions.json" -e "./Postman Collections/Environments/${{ github.event.inputs.network }}.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export "./${BRANCH}/latest/index.html" --reporter-htmlextra-darkTheme --reporter-htmlextra-showEnvironmentData --reporter-htmlextra-showGlobalData --reporter-htmlextra-logs --reporter-htmlextra-browserTitle "${GITHUB_SHA} on branch ${BRANCH_UNSANITIZED}" --reporter-htmlextra-title "0Chain API Regression Tests" --reporter-htmlextra-template "./Postman Collections/Data/0chain-dashboard-template.hbs"  --color on || exit_code=$? 
           exit $exit_code
    
      - name: Output the run Details
        if: always()
        uses: actions/upload-artifact@v2
        with: 
         name: RunReports
         path: "./${{ github.event.inputs.network }}/latest"
         
      - name: Deploy report page
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: test_reports
          keep_files: true
          github_token: "${{ secrets.SVC_ACCOUNT_SECRET }}"
          publish_dir: "./${{ github.event.inputs.network }}"
          destination_dir: "./${{ github.event.inputs.network }}"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"    
          
      - name: Report Link
        if: always()
        run: echo "https://0chain.github.io/blobber/${{ github.event.inputs.network }}/latest" 
